### ISSUE TITLE
Add way to get latest build number from a given build prefix

### ISSUE THREAD

**Issue by zlalanne** [ldiqual/buildnumber.io#2]
Would be nice to add a version prefix to the POST that could determine the correct build number to use.

For example:
I start development on version 1.1.0 of my app. I make a few builds so I get:
1.1.0.1
1.1.0.2
1.1.0.3

Now I make a significant change so I bump the minor number. The build number should reset:
1.1.1.1
1.1.1.2
1.1.1.3

Noe let's say something critical happened in the 1.1.0 release and I need to go back and fix it. I should be able to request a new "1.1.0" build and receive a 4, so that the next version number is:
1.1.0.4

**Comment by ldiqual** [comment]
That's a great idea! Both strategies are pretty common: 1) have a unique build number whatever the version is, or 2) have a build number that resets on each version. I'll do more thinking around this, but we could just have:

```
POST /package/builds // Strategy #1
POST /package/version/builds // Strategy #2
```

How does that sound?

**Comment by ldiqual** [comment]
@zlalanne I implemented the idea explained above. Let me know what you think!

**Comment by zlalanne** [comment]
Awesome! Like the new documentation too
